stages:
  - build
  - test

#before_script:
#  - export GRADLE_USER_HOME=`pwd`/.gradle
#
#cache:
#  paths:
#    - .gradle/wrapper
#    - .gradle/caches

gradle-build:
  stage: build
  image: openjdk:11-jdk-slim
  script: ./gradlew build

gradle-test1:
  stage: test
  needs: ["gradle-build"]
  image: openjdk:11-jdk-slim
  script: ./gradlew test

gradle-test2:
  stage: test
  needs: ["gradle-build"]
  image: openjdk:11-jdk-slim
  script: ./gradlew check
