stages:
  - build
  - test

gradle-build:
  stage: build
  image: openjdk:11-jdk-slim
  script: ./gradlew build

gradle-test:
  stage: test
  needs: ["gradle-build"]
  image: openjdk:11-jdk-slim
  script: ./gradlew test
