stages:
  - build
  - test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

image: openjdk:11-jdk-slim

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

gradle-build:
  stage: build
  script: ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar


gradle-test1:
  stage: test
  needs:
    - job: gradle-build
      artifacts: false
  script: ./gradlew test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml

gradle-test2:
  stage: test
  needs:
    - job: gradle-build
      artifacts: false
  script: ./gradlew check
