stages:
  - build
  - test
  - publish

variables:
  #  # Instruct Docker host to daemon of DinD.
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""


before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

image: openjdk:11-jdk-slim

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

gradle-build:
  stage: build
  script: ./gradlew build -x test
  artifacts:
    paths:
      - build/libs/*.jar


gradle-test:
  stage: test
  needs:
    - job: gradle-build
      artifacts: false
  script: ./gradlew test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml

docker-build:
  stage: publish
  needs:
    - job: gradle-build
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login $HARBOR_URL -u $HARBOR_ID -p $HARBOR_PASSWORD_TOKEN
  script:
    - docker pull $HARBOR_URL/$HARBOR_PROJECT/$CI_PROJECT_NAME:latest || true
    - docker build --cache-from $HARBOR_URL/$HARBOR_PROJECT/$CI_PROJECT_NAME:latest
      -t $HARBOR_URL/$HARBOR_PROJECT/$CI_PROJECT_NAME:latest .
    - docker push $HARBOR_URL/$HARBOR_PROJECT/$CI_PROJECT_NAME:latest
