stages:
  - build
  - test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

image: openjdk:11-jdk-slim

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

gradle-build:
  stage: build
  script: ./gradlew build -x test

gradle-test1:
  stage: test
  needs: ["gradle-build"]
  script: ./gradlew test

gradle-test2:
  stage: test
  needs: ["gradle-build"]
  script: ./gradlew check
